### ISSUE TITLE
Do we stick with centos or make the move to an ubuntu world?

### ISSUE THREAD

**Issue by jduckles** [ouinformatics/ccstack-docker#4]
In the case of docker containers I think it will be easier to set them up as ubuntu containers overall. As far as a machine hosting the containers, I could go either way, but probably lean toward centos docker container hosts. Thoughts?

**Comment by mbstacy** [comment]
I like CentOS. I use Ubuntu only when the application is developed in ubuntu (ie. qiime). I can do ubuntu, but like Centos.
